import tkinter
root = tkinter.Tk()
root.title("VollEfrei")
root.iconphoto(False, tkinter.PhotoImage(file="assets/volley-transparent.png"))
can = tkinter.Canvas(root, width=1280, height=720)
backGround = tkinter.PhotoImage(file="assets/fond_decran_volleyefrei_2.png")
width = backGround.width()
height = backGround.height()
can.create_image(width//2, height//2, image=backGround)
can.place(x=0,y=0)
root.geometry("%dx%d+0+0" % (width, height))
root.mainloop()